openapi: 3.1.0
info:
  title: "MineAuth"
  description: |
    This is the MineAuth API documentation.<br>
    This makes user access to self information on minecraft.
  license:
    name: CC0-1.0
    url: "https://creativecommons.org/publicdomain/zero/1.0/"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Local server"
  - url: "https://api.example.com"
    description: "Production server"

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/token
          refreshUrl: /oauth2/token
          scopes:
            profile: Grants read access for my profile
            all: Grants read access for my resources

security:
  - oauth2: [ openid, profile, all ]

paths:
  /oauth2/userinfo:
    get:
      summary: Get user information
      security:
        - oauth2: [ profile ]
  /oauth2/revoke:
    post:
      summary: Revoke access token
      security:
        - oauth2: [ all ]
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
  /oauth2/introspect:
    post:
      summary: Introspect access token
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
