site_name: Moripa-API Docs
theme:
  name: material
  language: ja
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary : green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary : green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: ja
repo_url: https://github.com/morinoparty/Moripa-API
repo_name: Moripa-API
copyright: No Rights Reserved.
