name: upload_release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: change plugin.yml version
        run: |
          before="${{ github.event.release.tag_name }}"
          after="${before//v/}"
          sed -i -e "s/1.0-SNAPSHOT/$after/i" './gradle.properties'

      - name: Build with Gradle
        run: ./gradlew :core:build -x test

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./core/build/libs/core-${{ github.event.release.tag_name }}.jar
          asset_name: MineAuth-core_all.jar
          asset_content_type: application/jar


